//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.WebSrvLMES {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebSrvLMES.OraPKGSoap")]
    public interface OraPKGSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test_DBConnect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test_DBConnect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sephiroth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Sephiroth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Select", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ora_Select(string[] User_Info, string StrQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_MultiSelect", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ora_MultiSelect(string[] User_Info, string[] StrDT, string[] StrQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Modify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Ora_Modify(string[] User_Info, string StrQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_MultiModify", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object Ora_MultiModify(string[] User_Info, string[] StrQry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Select_Procedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ora_Select_Procedure(string[] User_Info, System.Data.DataSet DS_Para);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Run_Procedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ora_Run_Procedure(string[] User_Info, System.Data.DataSet DS_Para);
        
        // CODEGEN: Parameter 'photo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Run_Procedure_Blob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Test.WebSrvLMES.Ora_Run_Procedure_BlobResponse Ora_Run_Procedure_Blob(Test.WebSrvLMES.Ora_Run_Procedure_BlobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ora_Modify_Procedure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Ora_Modify_Procedure(string[] User_Info, System.Data.DataSet DS_Data);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ora_Run_Procedure_Blob", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ora_Run_Procedure_BlobRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Procude_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] Parameter_Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int[] Parameter_Type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] Parameter_Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] photo;
        
        public Ora_Run_Procedure_BlobRequest() {
        }
        
        public Ora_Run_Procedure_BlobRequest(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, byte[] photo) {
            this.Procude_Name = Procude_Name;
            this.Parameter_Name = Parameter_Name;
            this.Parameter_Type = Parameter_Type;
            this.Parameter_Value = Parameter_Value;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ora_Run_Procedure_BlobResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Ora_Run_Procedure_BlobResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Ora_Run_Procedure_BlobResult;
        
        public Ora_Run_Procedure_BlobResponse() {
        }
        
        public Ora_Run_Procedure_BlobResponse(bool Ora_Run_Procedure_BlobResult) {
            this.Ora_Run_Procedure_BlobResult = Ora_Run_Procedure_BlobResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OraPKGSoapChannel : Test.WebSrvLMES.OraPKGSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OraPKGSoapClient : System.ServiceModel.ClientBase<Test.WebSrvLMES.OraPKGSoap>, Test.WebSrvLMES.OraPKGSoap {
        
        public OraPKGSoapClient() {
        }
        
        public OraPKGSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OraPKGSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OraPKGSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OraPKGSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string Test_DBConnect() {
            return base.Channel.Test_DBConnect();
        }
        
        public string Sephiroth() {
            return base.Channel.Sephiroth();
        }
        
        public System.Data.DataSet Ora_Select(string[] User_Info, string StrQry) {
            return base.Channel.Ora_Select(User_Info, StrQry);
        }
        
        public System.Data.DataSet Ora_MultiSelect(string[] User_Info, string[] StrDT, string[] StrQry) {
            return base.Channel.Ora_MultiSelect(User_Info, StrDT, StrQry);
        }
        
        public object Ora_Modify(string[] User_Info, string StrQry) {
            return base.Channel.Ora_Modify(User_Info, StrQry);
        }
        
        public object Ora_MultiModify(string[] User_Info, string[] StrQry) {
            return base.Channel.Ora_MultiModify(User_Info, StrQry);
        }
        
        public System.Data.DataSet Ora_Select_Procedure(string[] User_Info, System.Data.DataSet DS_Para) {
            return base.Channel.Ora_Select_Procedure(User_Info, DS_Para);
        }
        
        public System.Data.DataSet Ora_Run_Procedure(string[] User_Info, System.Data.DataSet DS_Para) {
            return base.Channel.Ora_Run_Procedure(User_Info, DS_Para);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.WebSrvLMES.Ora_Run_Procedure_BlobResponse Test.WebSrvLMES.OraPKGSoap.Ora_Run_Procedure_Blob(Test.WebSrvLMES.Ora_Run_Procedure_BlobRequest request) {
            return base.Channel.Ora_Run_Procedure_Blob(request);
        }
        
        public bool Ora_Run_Procedure_Blob(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, byte[] photo) {
            Test.WebSrvLMES.Ora_Run_Procedure_BlobRequest inValue = new Test.WebSrvLMES.Ora_Run_Procedure_BlobRequest();
            inValue.Procude_Name = Procude_Name;
            inValue.Parameter_Name = Parameter_Name;
            inValue.Parameter_Type = Parameter_Type;
            inValue.Parameter_Value = Parameter_Value;
            inValue.photo = photo;
            Test.WebSrvLMES.Ora_Run_Procedure_BlobResponse retVal = ((Test.WebSrvLMES.OraPKGSoap)(this)).Ora_Run_Procedure_Blob(inValue);
            return retVal.Ora_Run_Procedure_BlobResult;
        }
        
        public System.Data.DataSet Ora_Modify_Procedure(string[] User_Info, System.Data.DataSet DS_Data) {
            return base.Channel.Ora_Modify_Procedure(User_Info, DS_Data);
        }
    }
}
